### ISSUE TITLE
Get tests publishing again

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#11]
we had to disable them to get the build to work on azure pipelines.

Currently, the github pull_request action does not publish the test results and make it visible.  

Acceptance:  The test results are visible and can be easily checked after the action runs.

**Comment by breedx-nr** [comment]
We suspect that switching over to github actions (which we want to do anyway) might address this.

**Comment by abhihub** [comment]
Verify if it already works

**Comment by XiXiaPdx** [comment]
good question.  What does it mean to "publish" the test results?

**Comment by jkwatson** [comment]
> good question. What does it mean to "publish" the test results?

Being able to see them when looking at the PR, in a nice tabular form. JUnit has a standard way to do this; many CI systems will display the test results a link away from the PR.

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
