### ISSUE TITLE
Log.debug messages should not be logged at "Error" level

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/opentelemetry-exporter-java#114]
Issue:

When running with the  Opentelemetry Java Agent and this exporter, with the following log settings enabled

-Dio.opentelemetry.javaagent.slf4j.simpleLogger.log.com.newrelic.telemetry=debug
-Dnewrelic.enable.audit.logging=true"

Log.debug level messages from the underlying Telemetry SDK are appearing as "Error" level messages. 

<img width="1905" alt="Screen Shot 2020-10-29 at 11 36 11 AM" src="https://user-images.githubusercontent.com/24482401/97617770-6a7c5f00-19db-11eb-848f-f8d04ce95167.png">

https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/52ee0e995a20100ad490729f274957227fa7030b/telemetry-core/src/main/java/com/newrelic/telemetry/metrics/MetricBatchSender.java#L67

Investigate why that is happening

**Comment by breedx-nr** [comment]
Especially weird since it says DEBUG in the same line.  Could that red error mean stderr?

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
