### ISSUE TITLE
Add support to enable/disable Metrics for auto-instrumentation

### ISSUE THREAD

**Issue by matcouto** [newrelic/opentelemetry-exporter-java#140]
It would be nice to have a way of enabling/disabling exporters separately for **auto-instrumentation**, e.g. I have my Metrics already in place using something else and I only needed the Tracer from OpenTelemetry exporter.
Is there some sort of "workaround" for now that I could be using to disable Metrics?

**Comment by jasonjkeller** [comment]
@matcouto Perhaps, the [OTel Java agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation) provides a mechanism for disabling collection of certain telemetry types?

I'm not aware of a way to configure the auto-instrumentation exporter in that manner. 

Workarounds, off the top of my head (if the agent itself doesn't provide a mechanism):
* You could configure the `newrelic.metric.uri.override` property to use an invalid ingest endpoint and not send metrics. Unfortunately that wouldn't prevent the `MetricExporter` from doing work in the background. Not ideal.
* You could fork this project and build an artifact that doesn't bundle in the `MetricExporter` or better yet, submit a PR to configure it. :)

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
