### ISSUE TITLE
Update README to add pointer to NR integration bundle

### ISSUE THREAD

**Issue by jodeev** [newrelic/opentelemetry-exporter-java#144]
Now that there is a bundle package available for the Exporter + OTel agent, the README should include very obvious references to it in a few places. 

We want to prevent users that find this repo from getting all the way down the path of separately configuring the Exporter and an OTel agent and then later on discovering that there is an easy alternative that we never mentioned here!

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
