### ISSUE TITLE
Support usage by the auto-instrumentation agent

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#15]
In order to do this, it looks like we'll need to do three things:
1) publish a "fat jar" with all dependencies included
2) Create an exporter factory and make it loadable using SPI
3) Document configuration options and how to set them

**Comment by cmouli84** [comment]
This will be really helpful. Right now, I created a custom NewRelic SpanExporterFactory and using it for auto-instrumentation

**Comment by jkwatson** [comment]
@cmouli84 would you be willing to contribute that to this project? We'd love the contribution!

**Comment by cmouli84** [comment]
@jkwatson Sure, I can contribute to this project

**Comment by cmouli84** [comment]
@jkwatson Created PR #41 for add auto exporter support. Please provide feedback

**Comment by jkwatson** [comment]
closed with #41
