### ISSUE TITLE
[OTel Metrics] Oberserver data not included in export

### ISSUE THREAD

**Issue by bhollfreiheit** [newrelic/opentelemetry-exporter-java#150]
We're using metrics to capture custom telemetry data and send to New Relic. This works great for instruments of recorder type. But data of observer type instruments are not send. I'm creating the observer following the example on https://github.com/open-telemetry/opentelemetry-java/blob/main/QUICKSTART.md#metrics-alpha-only.
When adding logging to the callback (in newer version of OTel this is set using `AsynchronousInstrument.Builder.setUpdater`) I can see that the callback is invoked and produces values. 
So my guess is that the NR exporter is not yet supporting observer data, right?

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
