### ISSUE TITLE
Archive the OpenTelemetry Exporter repository

### ISSUE THREAD

**Issue by jodeev** [newrelic/opentelemetry-exporter-java#155]
Per comments on https://github.com/newrelic/opentelemetry-exporter-java/issues/146, we will archive this repository.

Update the README and find any links to this repo that are in the OpenTelemetry organization repository.

**Comment by jasonjkeller** [comment]
This project has been archived: https://github.com/newrelic/opentelemetry-exporter-java#archival-notice
