### ISSUE TITLE
exporter NOT compatible with latest release of opentelemetry-javaagent–all.jar

### ISSUE THREAD

**Issue by shyam1975** [newrelic/opentelemetry-exporter-java#156]
I believe there is a version conflict that is preventing the command from working. What is the right version of opentelemetry-javaagent–all.jar to work with the version of the exporter (0.13.1)?

java -javaagent:path/to/opentelemetry-javaagent–all.jar
-Dotel.exporter.jar=path/to/opentelemetry-exporter-newrelic-auto-.jar
-Dnewrelic.api.key=${INSIGHTS_INSERT_KEY}
-Dnewrelic.service.name=best-service-ever
-jar myapp.jar

**Comment by jasonjkeller** [comment]
@shyam1975 You are correct, the exporter doesn't support the latest versions of OpenTelemetry. The last published release supports up to OTel `v0.13.1`. The compatible versions can be found on the release: https://github.com/newrelic/opentelemetry-exporter-java/releases/tag/v0.13.0

That said, this Java specific exporter is going to be archived and no longer updated in favor of a more general solution that is more language agnostic.

The current recommended approach for ingesting OTel data into New Relic from the [OTel Java agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation/) is to use the [OpenTelemetry Collector](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic/#collector) and configure it to use the [New Relic exporter](https://github.com/newrelic-forks/opentelemetry-collector-contrib/tree/newrelic-main/exporter/newrelicexporter) that is specific to the collector.

**Comment by shyam1975** [comment]
@jasonjkeller thanks for the clarifications.

Another question on the compatibility. I am interested in testing out this java specific explorer, I understand this will be archived in the long run.

I looked at the release notes and it was NOT clear as to what versions are compatible. You are saying newrelic exporter 13.1 is compatible with which versions of opentelemetry-javaagent-all.jar ? v1.0.1 does NOT seem to be working.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases

**Comment by jasonjkeller** [comment]
@shyam1975 Sorry for the delayed response. If you look at the 0.13.x release note that I linked above it states that it supports up to 0.13.1 of the OTel SDK and OTel Java agent.

```
Minor compatibility updates in this release:

Updates compatibility with io.opentelemetry:opentelemetry-sdk:0.13.1
Updates compatibility with io.opentelemetry.javaagent:opentelemetry-javaagent-spi:0.13.1
Updates compatibility with com.newrelic.telemetry:telemetry::0.10.0
Updates compatibility with com.newrelic.telemetry:telemetry-http-okhttp::0.10.0
```
