### ISSUE TITLE
Open Telemetry Exporter Snapshot does not contain expected method: addSpanProcessor

### ISSUE THREAD

**Issue by litscher** [newrelic/opentelemetry-exporter-java#17]
I have been following this documentation:https://github.com/newrelic/opentelemetry-exporter-java#how-to-use.

I have added the lines into the gradle build:
```
implementation(“com.newrelic.telemetry:opentelemetry-exporters-newrelic:0.2.0-SNAPSHOT”)
implementation(“io.opentelemetry:opentelemetry-sdk:0.2.0”)
implementation(“com.newrelic.telemetry:telemetry-core:0.3.2”)
implementation(“com.newrelic.telemetry:telemetry-http-okhttp:0.3.2”)
```
However, step 3 of the implementation does not work. I have found that `addSpanProcessor` exists in the master branch of this repository but not the `opentelemetry-exporters-newrelic:0.2.0-SNAPSHOT`.

![image](https://user-images.githubusercontent.com/17788855/75993510-93d60100-5ec7-11ea-945c-c7c76cfaec42.png)

I have tried updating the packages and use `0.3.0-SNAPSHOT` as well as the `0.3.4` versions of the other implementations, but nothing has worked so far. 

Is there another library I should be importing?

**Comment by jkwatson** [comment]
Hi @litscher . Thanks for reporting this. I'll take a look ASAP and figure out what's going on.

**Comment by litscher** [comment]
I tried to take a look at the updated code and I am getting this when I run the gradle build:
```
A problem occurred evaluating root project 'icam-connector'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find opentelemetry-exporters-newrelic.jar (com.newrelic.telemetry:opentelemetry-exporters-newrelic:0.3.0-SNAPSHOT:20191014.202650-1).
     Searched in the following locations:
         https://oss.sonatype.org/content/repositories/snapshots/com/newrelic/telemetry/opentelemetry-exporters-newrelic/0.3.0-SNAPSHOT/opentelemetry-exporters-newrelic-0.3.0-20191014.202650-1.jar
```
That date tag does not match the one in the [repository]( https://oss.sonatype.org/content/repositories/snapshots/com/newrelic/telemetry/opentelemetry-exporters-newrelic/0.3.0-SNAPSHOT/)

**Comment by jkwatson** [comment]
You might need to force gradle to pull down refreshed its depedencies.

**Comment by litscher** [comment]
I have been unable to resolve these dependencies. I had someone with a different machine attempt to resolve them as well.

**Comment by jkwatson** [comment]
Can you point me at your code? This is working fine for me (and our CI system as well).

**Comment by litscher** [comment]
It is enterprise code so I cannot easily give it to you. For the gradle file we have, 
```
repositories {
    mavenCentral()
    maven {
        url = "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}
dependencies {
    implementation("com.newrelic.telemetry:opentelemetry-exporters-newrelic:0.3.0-SNAPSHOT")
    implementation("io.opentelemetry:opentelemetry-sdk:0.2.0")
    implementation("com.newrelic.telemetry:telemetry-core:0.3.2")
    implementation("com.newrelic.telemetry:telemetry-http-okhttp:0.3.2")
}
```
I have tried version 5.0.0 and 5.2.1

**Comment by jkwatson** [comment]
ok, I'll see if I can reproduce on our side. thanks for the snippet.

**Comment by jkwatson** [comment]
oh, I see. we have a typo in the README.  The most recent version we're publishing is is `0.2.0-SNAPSHOT`. Can you give that a whirl?

**Comment by litscher** [comment]
That definitely works.

**Comment by jkwatson** [comment]
great. I'll fix the README. Sorry for the trouble!

**Comment by litscher** [comment]
Thank you!!
