### ISSUE TITLE
When setting span.setStartTimestamp(long) no data comes through to the UI

### ISSUE THREAD

**Issue by litscher** [newrelic/opentelemetry-exporter-java#22]
Hello, 

I am currently finding that data does not make it to the UI if I use the setStartTimestamp. This works perfectly, but for odd duration times:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/17788855/76470428-7bce1800-63c6-11ea-9115-5174f18a9922.png">
This fails to appear on the UI altogether, but appears to send successfully: 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/17788855/76470535-c94a8500-63c6-11ea-9a30-2ce8c82ffab8.png">
Should I be using something different for setting the timestamp? Setting the end timestamp has no issues.

**Comment by jkwatson** [comment]
I believe that the metric API doesn't accept timestamps that are too far in the past. This could be your problem. Can you validate that your timestamps are recent?

**Comment by litscher** [comment]
Yes. The start time is within a minute, usually less.

**Comment by jkwatson** [comment]
Do you see any `NrIntegrationError` events?

**Comment by jkwatson** [comment]
Also, what does DEBUG logging with auditLogging enabled show about the payloads? Can you paste in a couple of payloads that aren't working?

**Comment by litscher** [comment]
I am not seeing any errors here. 
563 [pool-1-thread-1] DEBUG com.newrelic.telemetry.transport.BatchDataSender  - Sending json:
```json
 [{
	"common": {
		"attributes": {
			"service.name": "NEW-RELIC-TEST",
			"collector.name": "newrelic-opentelemetry-exporter",
			"instrumentation.provider": "opentelemetry"
		}
	},
	"spans": [{
		"id": "764821423f9b477b",
		"trace.id": "ee950b98a8ef38ad9f2474f95fc70c7f",
		"timestamp": 1584033280,
		"attributes": {
			"duration.ms": 2.78E-4,
			"instrumentation.version": "6.1.0.6",
			"component": "CICS",
			"system": "PLEX1/IPO1",
			"application": "CICS551",
			"name": "CSMI",
			"parent.id": "be1f76daf06da181",
			"instrumentation.name": "TESTConnect"
		}
	}, {
		"id": "c807144fedba2f6b",
		"trace.id": "ffa13f0eec2e4ff60768b1ac6057a246",
		"timestamp": 1584033280,
		"attributes": {
			"duration.ms": 2.78E-4,
			"instrumentation.version": "6.1.0.6",
			"component": "CICS",
			"system": "PLEX1/IPO1",
			"application": "CICS551",
			"name": "CSMI",
			"parent.id": "7a6c705ed73d17b7",
			"instrumentation.name": "TESTConnect"
		}
	}, {
		"id": "dfa9e3e9c14bba2b",
		"trace.id": "ffa13f0eec2e4ff60768b1ac6057a246",
		"timestamp": 1584033280,
		"attributes": {
			"duration.ms": 1.5824492098532896E12,
			"instrumentation.version": "6.1.0.6",
			"component": "VSAM",
			"system": "PLEX1/IPO1",
			"application": "VSAM",
			"name": "CSMI",
			"parent.id": "c807144fedba2f6b",
			"instrumentation.name": "TESTConnect"
		}
	}, {
		"id": "7a6c705ed73d17b7",
		"trace.id": "ffa13f0eec2e4ff60768b1ac6057a246",
		"timestamp": 1584033280,
		"attributes": {
			"duration.ms": 0.020954,
			"instrumentation.version": "6.1.0.6",
			"component": "ZCONN",
			"system": "nmp175",
			"application": "serverAPM",
			"name": "inquireSingle",
			"instrumentation.name": "TESTConnect"
		}
	}, {
		"id": "be48b1e839774721",
		"trace.id": "ee950b98a8ef38ad9f2474f95fc70c7f",
		"timestamp": 1584033280,
		"attributes": {
			"duration.ms": 1.582449209854826E12,
			"instrumentation.version": "6.1.0.6",
			"component": "VSAM",
			"system": "PLEX1/IPO1",
			"application": "VSAM",
			"name": "CSMI",
			"parent.id": "764821423f9b477b",
			"instrumentation.name": "TESTConnect"
		}
	}, {
		"id": "be1f76daf06da181",
		"trace.id": "ee950b98a8ef38ad9f2474f95fc70c7f",
		"timestamp": 1584033280,
		"attributes": {
			"duration.ms": 0.020954,
			"instrumentation.version": "6.1.0.6",
			"component": "ZCONN",
			"system": "nmp175",
			"application": "serverAPM",
			"name": "inquireSingle",
			"instrumentation.name": "TESTConnect"
		}
	}]
}]
```

**Comment by jkwatson** [comment]
It looks like your timestamps are in seconds since unix epoch, rather than `milliseconds`, which is what is required by the API. So, the API is almost certainly rejecting your spans as being far far in the past. 

Can you query `NrIntegrationError` events in Insights/NR-1 to confirm this is the case?

**Comment by litscher** [comment]
I think we might have been putting the dates in as microseconds. I am working with it now.

**Comment by litscher** [comment]
I am not getting any results on the `NrIntegrationError` when searching "everything" in New Relic One

**Comment by litscher** [comment]
This is our current start time stamp: 1584629120705. Thought it seems that we are not getting any data anymore so I am not sure what has happened on that front

**Comment by litscher** [comment]
Here are a few of our start times and end times. I am still getting the span times in seconds, though. 
```
Start: 1584630528705
End: 1584630528726
Start: 1584630528719
End: 1584630528719
```
Span: 
```json
"spans": [{
		"id": "302ebb268d16a74e",
		"trace.id": "a4ff75f0e8a038278c4e707799288ba8",
		"timestamp": 1584630,
		"attributes": {
			"duration.ms": 0.0,
			"component": "VSAM",
			"system": "PLEX1/IPO1",
			"application": "VSAM",
			"name": "CSMI",
			"parent.id": "096806a73f93b70e",
			"instrumentation.name": "testConnect"
		}
	}, ...
```

**Comment by jkwatson** [comment]
If you're recording the Spans using OpenTelemetry, the timestamps all need to be in nanoseconds since Unix epoch. It looks like yours are in millis.

**Comment by litscher** [comment]
This makes more sense and functions! Thank you for your time.

**Comment by jkwatson** [comment]
Glad it's working!
