### ISSUE TITLE
Add additional percentiles to the Summary metric export code.

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#27]
There is a TODO in the code to address this.  Nothing yet generates these percentiles, though.

**Comment by abhihub** [comment]
Is the case still that nothing is generating percentiles yet?

**Comment by jkwatson** [comment]
Yes, the java SDK does not have quantile or histogram support yet.

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
