### ISSUE TITLE
Support proxy config for Exporter

### ISSUE THREAD

**Issue by alaa-freiheit** [newrelic/opentelemetry-exporter-java#32]
We would like to be able to configure the okHttpClient with a proxy configuration because we are running in an environment with a proxy in between our services and newrelic and the proxy requires authentication.

**Comment by jeffalder** [comment]
Let me see if I can figure out the magic recipe.

**Comment by jeffalder** [comment]
@alaa-freiheit : I'm assuming you can create a properly-configured instance of `okhttp3.OkHttpClient`. Once you have that:

1. Create an `OkHttpPoster` with your `OkHttpClient`. (use this class: https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry-http-okhttp/src/main/java/com/newrelic/telemetry/OkHttpPoster.java#L29)
2. Call `SpanBatchSender.builder` with your `OkHttpPoster`, like this: https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry-http-okhttp/src/main/java/com/newrelic/telemetry/SimpleSpanBatchSender.java#L64
3. Call `MetricBatchSender.builder` with your `OkHttpPoster`, like this: https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry-http-okhttp/src/main/java/com/newrelic/telemetry/SimpleMetricBatchSender.java#L64
4. Create a `TelemetryClient` with the `SpanBatchSender` and `MetricBatchSender`, by calling this: https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java#L45
5. Set the `TelemetryClient` on the `NewRelicSpanExporter` via the builder: https://github.com/newrelic/opentelemetry-exporter-java/blob/master/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java#L94

Then you should be all set up. As I'm writing this, it seems fairly cumbersome, but it would be clearer and easier with Dagger or a similar DI framework.

**Comment by alaa-freiheit** [comment]
Thanks @jeffalder.
I'll try that out and report back.

**Comment by alaa-freiheit** [comment]
Thanks it it working now :)
