### ISSUE TITLE
the Telemetry SDK depends on gson

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#42]
This is a regression that happened in 0.5.0. The SDK now has a hard dependency on the gson library, instead of including the 2 classes needed to do the json processing.

**Comment by jeffalder** [comment]
Changed here: https://github.com/newrelic/newrelic-telemetry-sdk-java/pull/149

**Comment by jkwatson** [comment]
Yep. I think it never got built in to the release process, unfortunately.

**Comment by jkwatson** [comment]
This is really a bug in the telemetry SDK itself, so I'm closing this one in favor of https://github.com/newrelic/newrelic-telemetry-sdk-java/issues/157
