### ISSUE TITLE
No data reporting in Test App -

### ISSUE THREAD

**Issue by twestdavis** [newrelic/opentelemetry-exporter-java#46]
Created ticket: https://newrelic.zendesk.com/agent/tickets/403029
Advised to submit issue here:
Customer is running on his local environment using the open telemetry exporter (https://github.com/newrelic/opentelemetry-exporter-java), but no data is reporting. He turned off the java agent to verify data shown was actually being sent via open telemetry exporter and not the agent.

**Comment by jkwatson** [comment]
First steps: make sure you have slf4j logging enabled at DEBUG for `com.newrelic.telemetry` and have enabled debug logging for the exporter. Take a look at the resulting logs and make sure that data is flowing, without errors to the New Relic APIs. Let me know what you see in the logs.

**Comment by breedx-nr** [comment]
@twestdavis Does this look like it is done for you?

**Comment by jkwatson** [comment]
bump @twestdavis Can we close this?

**Comment by twestdavis** [comment]
Yes, this can be closed. Thank you!


Taylor West *Davis | **Senior Solutions Consultant*

<http://www.newrelic.com>
