### ISSUE TITLE
Newrelic auto exporter seems to conflict with logic to set up open tracing

### ISSUE THREAD

**Issue by dougschroeder** [newrelic/opentelemetry-exporter-java#50]
The [auto instrumentation](https://github.com/newrelic/opentelemetry-exporter-java#auto-instrumentation) section readme page for this project says you can use the auto exporter to instrument using the [opentelemetry-auto-instr-java](https://github.com/open-telemetry/opentelemetry-auto-instr-java) library. I tried adding the following:

```
-javaagent:${myPath}/newrelic/opentelemetry-auto-0.3.0.jar -Dota.exporter.jar=${myPath}/newrelic/opentelemetry-exporters-newrelic-auto-0.4.0.jar -Dota.exporter.newrelic.api.key=${myInsightsKey} -Dota.exporter.newrelic.service.name=${myAppName}
```

I have this logic, which is described in Step 3 of the [for spans](https://github.com/newrelic/opentelemetry-exporter-java#for-spans) section of the readme page:

```
 TracerSdkProvider tracerSdkProvider = (TracerSdkProvider) OpenTelemetry.getTracerProvider();
    tracerSdkProvider.addSpanProcessor(spanProcessor);
```

I get the following when that code is run:

```
[793010A4] java.lang.ClassCastException: io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracerProvider cannot be cast to io.opentelemetry.sdk.trace.TracerSdkProvider
```

Is there anything I need to do differently to get around this issue? Thank you!

-Doug

**Comment by jkwatson** [comment]
Hi Doug. Sorry for the confusion here. I'll get the docs updated.  When you use the auto-instrumentation agent, it does all the SDK setup for you, via the jar we provide. And, it intentionally makes it impossible for you to configure a second SDK. So, you should be able to jump to just doing the instrumentation, and remove all of the SDK configuration parts of the README.

I'll make sure to get the docs clarified on this point. Thanks for the report! Let me know if there is any further confusion.

**Comment by dougschroeder** [comment]
Thank you John! I should have thought to try that. Thank you for the clarification.

**Comment by jkwatson** [comment]
See PR #51 for the documentation update.
