### ISSUE TITLE
New Relic API. Aborting metric batch send

### ISSUE THREAD

**Issue by CHHUM** [newrelic/opentelemetry-exporter-java#58]
The [auto instrumentation section readme](https://github.com/newrelic/opentelemetry-exporter-java#auto-instrumentation) page for this project says you can use the auto exporter to instrument using the opentelemetry-auto-instr-java library. 

I tried adding the following:
`-javaagent:${myPath}/newrelic/opentelemetry-auto-0.3.0.jar -Dota.exporter.jar=${myPath}/newrelic/opentelemetry-exporters-newrelic-auto-0.4.0.jar -Dota.exporter.newrelic.api.key=${myInsightsKey} -Dota.exporter.newrelic.service.name=${myAppName}`

I get the following when that code is run:
_[opentelemetry.auto.trace 2020-06-08 11:53:11:123 +0100] [pool-1-thread-1] ERROR com.newrelic.telemetry.TelemetryClient - Received a fatal exception from the New Relic API. Aborting metric batch send.
com.newrelic.telemetry.exceptions.DiscardBatchException: The New Relic API failed to process this request and it should not be retried.
	at com.newrelic.telemetry.transport.BatchDataSender.sendPayload(BatchDataSender.java:132)
	at com.newrelic.telemetry.transport.BatchDataSender.send(BatchDataSender.java:81)
	at com.newrelic.telemetry.spans.SpanBatchSender.sendBatch(SpanBatchSender.java:52)
	at com.newrelic.telemetry.TelemetryClient.lambda$sendBatch$1(TelemetryClient.java:68)
	at com.newrelic.telemetry.TelemetryClient.sendWithErrorHandling(TelemetryClient.java:91)
	at com.newrelic.telemetry.TelemetryClient.lambda$scheduleBatchSend$2(TelemetryClient.java:85)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)_
I got the API insight Key from New Relic One via Account Settings…API Keys…Insights API keys which I assume is the right place?  The documentation I followed lead me to a [dead (for me, at least) link](https://insights.newrelic.com/) that states "account access denied: no account found"

Is there something else I need to do?  Are the versions incompatible?

**Comment by jkwatson** [comment]
@CHHUM Thanks for reaching out with the question. Did you use an Insights _Insert_ key, or a query key? The insert key is the one that is required.

Can you also try turning on DEBUG level logging for the `com.newrelic.telemetry` package? If logging is working (and I have had troubles with logging working with the 0.3.0 version of the otel-auto project), then we should get more details about why the request is being rejected.

**Comment by CHHUM** [comment]
Thanks so much for your reply.  I did check it was a valid insert key by sending some test JSON across using curl - 
`gzip -c example_events.json | curl --data-binary @- -X POST -H "Content-Type: application/json" -H "X-Insert-Key: My Key" -H "Content-Encoding: gzip" https://insights-collector.eu01.nr-data.net/v1/accounts/myaccount/events`
Which works.

Sorry - I feel like I should be able to work this out but how do I get debug level logging on from the command line?

**Comment by jkwatson** [comment]
> Sorry - I feel like I should be able to work this out but how do I get debug level logging on from the command line?

Our exporter and telemetry SDK both use slf4j API for logging, so that will depend, I guess, on what slf4j implementation is being used by the agent. This might be a question for the OpenTelemetry java instrumentation group. Do you mind asking over here: https://gitter.im/open-telemetry/opentelemetry-java-instrumentation ?

**Comment by CHHUM** [comment]
No problem - I've asked

**Comment by jkwatson** [comment]
@CHHUM ok! Based on @trask's help, it looks like this is what you want:

`-Dio.opentelemetry.auto.slf4j.simpleLogger.log.com.newrelic.telemetry=debug -Dota.exporter.newrelic.enable.audit.logging=true`

**Comment by CHHUM** [comment]
Thank you so much for all your help with this.  I am getting a 403 back so presumably an authentication issue.
Log attached.  
Is is because I'm in Europe or because I only have a free New Relic One account.
If was sending data via curl I'd use something like
gzip -c example_events.json | curl --data-binary @- -X POST -H "Content-Type: application/json" -H "X-Insert-Key: MY-KEY" -H "Content-Encoding: gzip" https://insights-collector.eu01.nr-data.net/v1/accounts/2751078/events

rather than sending to the https://trace-api.newrelic.com/trace/v1 end point
[nr-log.log](https://github.com/newrelic/opentelemetry-exporter-java/files/4752740/nr-log.log)

**Comment by jkwatson** [comment]
Yes, if you currently only have a free account, I don't think the trace and metrics APIs are available. Can you try signing up for a Insights Pro trial and see if it works for you?

**Comment by CHHUM** [comment]
I do have an Insights Pro Trail as part of the New Relic One free account:
<img width="883" alt="Screenshot 2020-06-09 at 16 37 28" src="https://user-images.githubusercontent.com/841966/84168645-8e142c80-aa6f-11ea-8aa5-dc75c0b6d4ef.png">

**Comment by jkwatson** [comment]
hm. interesting. I'll reach out internally and see if I can figure out next steps for debugging this auth issue. Not really my area of expertise. :)

**Comment by CHHUM** [comment]
Thank you - let me know if I can reach out to someone else directly!

**Comment by jkwatson** [comment]
I reached out to some internal folks, and they say you might need the "APM Pro" trial to get the trace API as well. Can you try adding that trial and see if it works? If you need help with that, reaching out to New Relic support is probably your best bet.

**Comment by CHHUM** [comment]
Will do - thank you.  I was going to submit a PR for the readme to include debug and audit logging but I see you've already updated it.

**Comment by CHHUM** [comment]
Just an update to say I am still stuck with this. One question is would it matter if my New Relic account is in the EU?  Are the endpoints different?

**Comment by jkwatson** [comment]
🤦  I was totally unaware that there's a separate endpoint for EU ingest (and our docs don't mention this, either).  Can you try overriding the URI to `https://trace-api.eu.newrelic.com/` and see if that works?

**Comment by jkwatson** [comment]
(and for metrics, I think you'll want `https://metric-api.eu.newrelic.com/`

**Comment by jkwatson** [comment]
FYI, I found our docs for all of the EU API endpoints:  https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/our-eu-us-region-data-centers#endpoints

**Comment by jkwatson** [comment]
And, just FYI, I opened up an issue with our telemetry SDK to make it easy to select the EU region. We would then want to propagate that up to the exporters once it is in place:  https://github.com/newrelic/newrelic-telemetry-sdk-java/issues/188

**Comment by CHHUM** [comment]
Thank you. I've tried running this adding the argument
 -Dota.exporter.newrelic.uri.override=https://trace-api.eu.newrelic.com/ 
But I still get a 403.

_Logging suggests that this has been picked up:
[opentelemetry.auto.trace 2020-06-12 17:20:53:371 +0100] [main] INFO com.newrelic.telemetry.transport.BatchDataSender - **BatchDataSender configured with endpoint https://trace-api.eu.newrelic.com/trace/v1**
[opentelemetry.auto.trace 2020-06-12 17:20:53:372 +0100] [main] INFO com.newrelic.telemetry.transport.BatchDataSender - BatchDataSender configured with audit logging enabled.
[opentelemetry.auto.trace 2020-06-12 17:20:53:414 +0100] [main] INFO io.opentelemetry.auto.tooling.TracerInstaller - Installed span exporter: com.newrelic.telemetry.opentelemetry.export.NewRelicSpanExporter
[opentelemetry.auto.trace 2020-06-12 17:20:53:417 +0100] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: 0.3.0~f4fde658d_

However I am still setting the 403 at the end of it.  
[opentelemetry.auto.trace 2020-06-12 17:20:58:746 +0100] [pool-1-thread-1] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API: code: 403, body: {}
[opentelemetry.auto.trace 2020-06-12 17:20:58:746 +0100] [pool-1-thread-1] WARN com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API. Discarding batch recommended.: code: 403, body: {}
[opentelemetry.auto.trace 2020-06-12 17:20:58:746 +0100] [pool-1-thread-1] ERROR com.newrelic.telemetry.TelemetryClient - Received a fatal exception from the New Relic API. Aborting metric batch send.
com.newrelic.telemetry.exceptions.DiscardBatchException: The New Relic API failed to process this request and it should not be retried.
	at com.newrelic.telemetry.transport.BatchDataSender.sendPayload(BatchDataSender.java:132)
	at com.newrelic.telemetry.transport.BatchDataSender.send(BatchDataSender.java:81)
	at com.newrelic.telemetry.spans.SpanBatchSender.sendBatch(SpanBatchSender.java:52)
	at com.newrelic.telemetry.TelemetryClient.lambda$sendBatch$1(TelemetryClient.java:68)
	at com.newrelic.telemetry.TelemetryClient.sendWithErrorHandling(TelemetryClient.java:91)
	at com.newrelic.telemetry.TelemetryClient.lambda$scheduleBatchSend$2(TelemetryClient.java:85)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

I'm honestly a bit lost as to what else to try from here.

**Comment by jkwatson** [comment]
It looks like your account still doesn't have the APM Pro enabled. I'm 99.9% sure that's the problem here. I'm hoping support can help you get that straightened out.

**Comment by CHHUM** [comment]
We got there in the end.  Rather embarrassingly the last piece of the puzzle was a typo in the command line I was using - I had {} around the key.  I had tested both versions at some point, but I think I did that before we worked out how the URI override works - sorry!

**Comment by jkwatson** [comment]
woot! Glad you got it working!
