### ISSUE TITLE
When service.name is a required Resource attribute, remove from the exporter configurations

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#62]
It's spec'd as required, but not implemented as such at the moment. But, let's not lose track of the issue!

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
