### ISSUE TITLE
Consider grouping spans and metrics by Resource and sending separate batches for each Resource.

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#67]
We could potentially cut down drastically on the number of bytes being sent to the backend (after decompression) if we group the data by the Resource, and send the Resource attributes in the common block of the telemetry.

Most cases will end up with only one batch, but the reduction in copied data could potentially alleviate some pressure on the ingest pipeline while decompressing the data.

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
