### ISSUE TITLE
opentracing support

### ISSUE THREAD

**Issue by jaecktec** [newrelic/opentelemetry-exporter-java#71]
I am trying to hook this up with the micronaut-tracing support. Is it by any chance possible to get a 
`io.opentracing.Tracer` to hook up with the opentracing api?

**Comment by jkwatson** [comment]
Hello, @jaecktec . I think you might be looking for the opentracing-shim in the OpenTelemetry project itself. See here:  https://github.com/open-telemetry/opentelemetry-java/blob/6e7f34dd04697d7544bfc3518639f356173d6cec/opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/TraceShim.java#L35

**Comment by jaecktec** [comment]
Oh yes thank you! I was looking for that for days!
