### ISSUE TITLE
Add support for exporting array-valued Span Attributes

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#75]
What should we do with them? Probably turn them into comma-separated strings?

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
