### ISSUE TITLE
Add an example of using the exporter with auto-instrumentation

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#94]
It might be nice to have an example that uses the `@WithSpan` annotation, and maybe one with New Relic's `@Trace` annotation, too, since the agent supports it.

**Comment by jasonjkeller** [comment]
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.
